from handlers.admin_handlers.add_account import *
from handlers.admin_handlers.add_product import *
from handlers.admin_handlers.add_category import *
from handlers.admin_handlers.delete_product import *
from handlers.admin_handlers.delete_category import *
from handlers.admin_handlers.change_cat import *
from handlers.admin_handlers.change_product import *
from handlers.admin_handlers.add_main_category import *
from handlers.admin_handlers.delete_main_category import *
from handlers.admin_handlers.main_admin_keyboard_handlers import *
from handlers.admin_handlers.change_main_category import *
from handlers.admin_handlers.view_statistic import *
